<?PHP
# Mensagens de sistema
define('MSG001', 'Operação realizada com sucesso!');
define('MSG002', 'Operação não pode ser realizada!');

# Demandas PAR
if ($_SESSION['baselogin'] == 'simec_desenvolvimento') {

    define("DBLINK_PARAM_PDEINTERATIVO", 'dbname=dbpdeinterativo_hmg
											hostaddr=192.168.222.45
											user=simec
											password=phpsimecao
											port=5433');

    define('WF_TPDID_DEMANDA', 119);

    /*
     * INICIO de estados do documento da demanda
     * _____________________________________________________________________________
     */

    define("PAR_WF_DEMANDA_ESTADO_EM_CADASTRAMENTO", 778); # Envia para AGUARDANDO_ATENDIMENTO
    define("PAR_WF_DEMANDA_ESTADO_AGUARDANDO_ATENDIMENTO", 746); # Envia para ANALISE_DE_ATENDIMENTO
    define("PAR_WF_DEMANDA_ESTADO_EM_ANALISE_DE_ATENDIMENTO", 747); # Envia para ATENDIMENTO ou EM_DILIGENCIA
    define("PAR_WF_DEMANDA_ESTADO_EM_ATENDIMENTO", 749); # Envia para EM_DILIGENCIA ou EM_PAUSA ou AGUARDANDO_VALIDACAO
    define("PAR_WF_DEMANDA_ESTADO_EM_PAUSA", 752); # Volta para EM_ATENDIMENTO
    define("PAR_WF_DEMANDA_ESTADO_EM_DILIGENCIA", 748); # Volta para ANALISE_DE_ATENDIMENTO
    define("PAR_WF_DEMANDA_ESTADO_AGUARDANDO_VALIDACAO", 750); # Envia para ESTADO_CONCLUIDO
    define("PAR_WF_DEMANDA_ESTADO_CONCLUIDO", 751);# Nao pode mais fazer nada.
} else {
    if (IS_PRODUCAO) {
        define("DBLINK_PARAM_PDEINTERATIVO", 'dbname=dbsimec_pde
											hostaddr=192.168.222.184
											user=seguranca
											password=123seg
											port=5432');
    } else {
        define("DBLINK_PARAM_PDEINTERATIVO", 'dbname=dbpdeinterativo_hmg
											hostaddr=192.168.222.45
											user=simec
											password=phpsimecao
											port=5433');
    }
    define('WF_TPDID_DEMANDA', 127);

    /*
     * INICIO de estados do documento da demanda
     * _____________________________________________________________________________
     */

    define("PAR_WF_DEMANDA_ESTADO_EM_CADASTRAMENTO", 829);# Envia para AGUARDANDO_ATENDIMENTO
    define("PAR_WF_DEMANDA_ESTADO_AGUARDANDO_ATENDIMENTO", 830); # Envia para ANALISE_DE_ATENDIMENTO
    define("PAR_WF_DEMANDA_ESTADO_EM_ANALISE_DE_ATENDIMENTO", 831); # Envia para ATENDIMENTO ou EM_DILIGENCIA
    define("PAR_WF_DEMANDA_ESTADO_EM_DILIGENCIA", 832); # Volta para ANALISE_DE_ATENDIMENTO
    define("PAR_WF_DEMANDA_ESTADO_EM_ATENDIMENTO", 833); # Envia para EM_DILIGENCIA ou EM_PAUSA ou AGUARDANDO_VALIDACAO
    define("PAR_WF_DEMANDA_ESTADO_AGUARDANDO_VALIDACAO", 834); # Envia para ESTADO_CONCLUIDO
    define("PAR_WF_DEMANDA_ESTADO_CONCLUIDO", 835); # Nao pode mais fazer nada.
    define("PAR_WF_DEMANDA_ESTADO_EM_PAUSA", 836);# Volta para EM_ATENDIMENTO
}
/*
 * FIM de estados do documento da demanda
 * _____________________________________________________________________________
 */

define("SISID_PAR", 23);

#Termo de Compromisso
define("TIPO_TERMO", 1);

# TIPOS DE IMPRESSÃO DO TERMO
define("TIPO_IMPRESSAO_TERMO_REGERAR", 1);

# Intrumento diagnóstico
define("INSTRUMENTO_DIAGNOSTICO_ESTADUAL", 1);
define("INSTRUMENTO_DIAGNOSTICO_MUNICIPAL", 2);
define("STATUS_SUBACAO_EM_REFORMULACAO", 20);
define("STATUS_SUBACAO_EM_DILIGENCIA_REPROGRAMACAO", 23);

/*
 * PERFIS
 */
define("PAR_PERFIL_SUPER_USUARIO", 441);
define("PAR_PERFIL_TECNICO_PRORROGACAO", 1476 );
define("AEDID_REABRIR_PRORROGACAO", 4138 );
define("AEDID_DEFERIDO_PARA_INDEFERIDO", 4591  );
define("PAR_PERFIL_CONTROLE_USUARIO", 1416 );
define("PAR_PERFIL_NUTRICIONISTA", 1374);
define("PAR_PERFIL_ADMINISTRADOR", 459);
if ($_SESSION['baselogin'] == 'simec_desenvolvimento') {
    define("PAR_PERFIL_DEMANDANTE_PAR", 938);
} else {
    define("PAR_PERFIL_DEMANDANTE_PAR", 1012);
}
define("PAR_PERFIL_EQUIPE_FINANCEIRA", 458);
define("PAR_PERFIL_EQUIPE_MUNICIPAL", 460);
define("PAR_PERFIL_EQUIPE_MUNICIPAL_APROVACAO", 674);
define("PAR_PERFIL_PREFEITO", 556);
define("PAR_PERFIL_EQUIPE_ESTADUAL", 461);
define("PAR_PERFIL_EQUIPE_ESTADUAL_APROVACAO", 672);
// define("PAR_PERFIL_EQUIPE_ESTADUAL_SECRETARIO", 673); /**O valor 673 não era mais utilizado, porque está inativo, apesar de ser validado em diversos locais, caso alguém insira um usuário como secretário o valor no sistema é o 884*/
define("PAR_PERFIL_EQUIPE_ESTADUAL_SECRETARIO", 884);
define("PAR_PERFIL_EQUIPE_TECNICA", 457);
define("PAR_PERFIL_ENGENHEIRO_FNDE", 468); # Analista Técnico de Obras - FNDE
define("PAR_PERFIL_COORDENADOR_GERAL", 477); # Coordenador Técnico de Obras - FNDE
define("PAR_PERFIL_COORDENADOR_TECNICO", 478);
define("PAR_PERFIL_CONSULTA", 484);
define("PAR_PERFIL_CONSULTA_ESTADUAL", 488);
define("PAR_PERFIL_CONSULTA_MUNICIPAL", 489);
define("PAR_PERFIL_CONTROLE_SOCIAL_ESTADUAL", 1415);
define("PAR_PERFIL_CONTROLE_SOCIAL_MUNICIPAL", 1414);
define("PAR_PERFIL_ANALISE_PI", 587);
define("PAR_PERFIL_PROFUNC_PREANALISEPF", 539);
define("PAR_PERFIL_PROFUNC_ANALISEPF", 540);
define("PAR_PERFIL_PROFUNC_PREANALISEPF_TUTOR", 546);
define("PAR_PERFIL_PROFUNC_ANALISEPF_TUTOR", 548);
define("PAR_PERFIL_MANUTENCAO_TABELAS_APOIO", 545);
define("PAR_PERFIL_PAGADOR", 669);
define("PAR_PERFIL_ANALISTA_MERITOS", 689);
define("PAR_PERFIL_ANALISTA_QUESTOES_PONTUAIS", 685);
define("PAR_PERFIL_EMPENHADOR", 670);
define("PAR_PERFIL_GERADOR_DOCUMENTO", 671);
define("PAR_PERFIL_ALTA_GESTAO_MEC", 706);
define("PAR_PERFIL_ADMINISTRADOR_PROCESSOS", 805);
define("PAR_PERFIL_UNIVERSIDADE_ESTADUAL", 853);
define("PAR_PERFIL_PARLAMENTAR", 876);
define("PAR_PERFIL_ORGAO_CONTROLE", 877);
define("PAR_PERFIL_ADM_OBRAS", 882);
//define("PAR_PERFIL_SECRETARIO_ESTADUAL_EDUCACAO",	884);
define("PAR_PERFIL_SECRETARIO_ESTADUAL_EDUCACAO", 672);
define("PAR_PERFIL_SECRETARIO_ESTADUAL_SAUDE", 887);
define("PAR_PERFIL_ORGAO_DE_CONTROLE", 1094);
define("PAR_PERFIL_ENTIDADE_EXECUTORA", 1141);
define("PAR_PERFIL_ANALISTA_TR", 1194);
define("PAR_PERFIL_RESCISAO_DOCUMENTOS", 1429);
define("PAR_PERFIL_ADMINISTRADOR_REPROGRAMAÇÃO", 1224);
define("PAR_PERFIL_PRESIDENTE", 1503);
define("PAR_PERFIL_CONSELHEIRO", 1504 );
define("PAR_PERFIL_ASSESSOR_DIGAP", 1542 );
define("PAR_PERFIL_ANALISTA_PRESTACAO_CONTAS", 1799); # Analista do prestação de contas, insere efeito suspensivo
/* Aqui classificação da omissão do CACS*/
define("ROPID_GESTOR_UNIDADE", 1 );
define("ROPID_PRESIDENTE", 2 );


define("GRUPO_DE_PERFIL_MUNICIPAL_EDICAO", serialize(ARRAY(PAR_PERFIL_EQUIPE_MUNICIPAL, PAR_PERFIL_EQUIPE_MUNICIPAL_APROVACAO, PAR_PERFIL_PREFEITO)));
define("GRUPO_DE_PERFIL_ESTADUAL_EDICAO", serialize(ARRAY(PAR_PERFIL_EQUIPE_ESTADUAL, PAR_PERFIL_EQUIPE_ESTADUAL_APROVACAO, PAR_PERFIL_EQUIPE_ESTADUAL_SECRETARIO)));

define("GRUPO_DE_PERFIL_ESTADUAL", serialize(ARRAY(
PAR_PERFIL_PREFEITO,
PAR_PERFIL_EQUIPE_ESTADUAL_BRASIL_PRO,
PAR_PERFIL_EQUIPE_ESTADUAL_APROVACAO_BRASIL_PRO,
PAR_PERFIL_EQUIPE_ESTADUAL_APROVACAO,
PAR_PERFIL_EQUIPE_ESTADUAL,
PAR_PERFIL_CONSULTA_ESTADUAL,
PAR_PERFIL_CONTROLE_SOCIAL_ESTADUAL,
PAR_PERFIL_SECRETARIO_ESTADUAL_EDUCACAO)));

define("GRUPO_DE_PERFIL_MUNICIPAL", serialize(ARRAY(
PAR_PERFIL_EQUIPE_MUNICIPAL,
PAR_PERFIL_CONSULTA_MUNICIPAL,
PAR_PERFIL_CONTROLE_SOCIAL_MUNICIPAL,
PAR_PERFIL_EQUIPE_MUNICIPAL_APROVACAO)));

# PERFIS BRASIL PRO
define("PAR_PERFIL_EQUIPE_ESTADUAL_BRASIL_PRO", 838);
define("PAR_PERFIL_EQUIPE_ESTADUAL_APROVACAO_BRASIL_PRO", 839);

# PERFIL EJA
define("PAR_PERFIL_ANALISTA_EJA", 1080);

# PERFIL MAIS MÉDICOS.
define("PAR_PERFIL_AVAL_INSTITUCIONAL_MM", 1153);

# Tipo de dados da unidade
define("GOVERNO_ESTADUAL_MUNICIPAL", 1);
define("DIRIGENTE_ESTADUAL_MUNICIPAL", 2);
define("EQUIPE_LOCAL", 3);
define("COMITE_LOCAL_INTEGRANTES", 4);
define("COMITE_LOCAL_COORDENADOR", 5);

define("ALIMENTACAO_ESCOLAR_TECNICO_NUTRICIONISTA", 11);
define("ALIMENTACAO_ESCOLAR_NUTRICIONISTA", 12);



# Forma de execução proposta subação do guia
define("FORMA_EXECUCAO_ACAO_PAC", 1);
define("FORMA_EXECUCAO_ASSITENCIA_TECNICA", 2);
define("FORMA_EXECUCAO_TRANSFERENCIA_VOLUNTARIA", 3);
define("FORMA_EXECUCAO_EXECUTADA_PELO_MUNICIPIO", 4);
define("FORMA_EXECUCAO_FINANCIAMENTO_BNDES", 5);
define("FORMA_EXECUCAO_ASSISTENCIA_FINANCEIRA", 6);
define("FORMA_EXECUCAO_ASSISTENCIA_FINANCEIRA_OBRAS", 11);
define("FORMA_EXECUCAO_EXECUTADA_PELO_ESTADO", 12);
define("ASSISTENCIA_FINANCEIRA_EXTRAORDINARIA", 13);
define("ASSISTENCIA_FINANCEIRA_EMENDA", 14);
define("ASSISTENCIA_FINANCEIRA_EMENDA_OBRAS", 15);
define("ASSISTENCIA_FINANCEIRA_BRASIL_PRO", 16);
define("ASSISTENCIA_FINANCEIRA_BRASIL_PRO_OBRAS", 17);
define("ASSISTENCIA_FINANCEIRA_MOB_EQUIPE_PROINFANCIA", 18);

# Fase do Workflow
define("ELABORACAO", 451);
define("ANALISE", 452);
define("GERACAO_TERMO_COOPERACAO", 453);
define("DILIGENCIA", 454);
define("AGUARDANDO_ANALISE_GESTOR", 455);
define("EMPENHO", 456);
define("PAGAMENTO", 457);
define("INDEFERIDA", 458);
define("EM_ANALISE_COMISSAO", 462);

# Filtros de Subações para Lista Agrupada
define("SUBACOES_ANALISADAS", 1);
define("SUBACOES_PENDENTESDEANALISE", 2);
define("SUBACOES_GERADOTERMO", 3);
define("SUBACOES_CONVENIADA", 4);
define("SUBACOES_COMITENS", 5);
define("SUBACOES_SEMITENS", 6);
define("SUBACOES_COM_OBRAS", 7);

# Tipo de Subação
define("FORMA_EXECUCAO_EXECUTADA_PELO_MUNICIPIO_SEM_ITENS", 42);
define("FORMA_EXECUCAO_EXECUTADA_PELO_MUNICIPIO_COM_ITENS", 43);
define("FORMA_EXECUCAO_EXECUTADA_PELO_ESTADO_SEM_ITENS", 46);
define("FORMA_EXECUCAO_EXECUTADA_PELO_ESTADO_COM_ITENS", 45);
define("FORMA_EXECUCAO_ASSISTENCIA_FINANCEIRA_OBRAS_AMPLIACAO_ESCOLAS", 17);
define("FORMA_EXECUCAO_ASSISTENCIA_FINANCEIRA_OBRAS_REFORMA_ESCOLAS", 16);
define("FORMA_EXECUCAO_ASSISTENCIA_FINANCEIRA_OBRAS_CONSTRUCAO_ESCOLAS", 15);
define("FORMA_EXECUCAO_ASSISTENCIA_FINANCEIRA_BRASIL_PRO_COM_ITENS", 61);
define("FORMA_EXECUCAO_ASSISTENCIA_FINANCEIRA_BRASIL_PRO_FORMACAO", 81);
define("FORMA_EXECUCAO_ASSISTENCIA_FINANCEIRA_BRASIL_PRO_SEM_ITENS", 62);

# Tipo de obra da subação PTOID
define("OBRA_TIPO_A", 1);
define("OBRA_TIPO_B", 2);
define("OBRA_TIPO_C", 3);
define("OBRA_QUADRA_COBERTURA", 5);
define("OBRA_TIPO_C_220v", 6);
define("OBRA_TIPO_B_220v", 7);
define("OBRA_QUADRA_COBERTA_PROJETO_PROPRIO", 9);
define("OBRA_COBERTURA_PEQUENA", 23);
define("OBRA_COBERTURA_GRANDE", 28);
define("OBRA_COBERTURA_VESTIARIO", 27);
define("OBRA_TIPO_B_NOVO", 38);
define("OBRA_TIPO_C_NOVO", 39);
define("OBRA_TIPO_ESCOLA_PROINFANCIA_B_MI", 43);
define("OBRA_TIPO_ESCOLA_PROINFANCIA_C_MI", 42);
define("OBRA_TIPO_ESCOLA_PROINFANCIA_B_MI_EMENDA", 44);
define("OBRA_TIPO_ESCOLA_PROINFANCIA_C_MI_EMENDA", 45);
define("OBRA_TIPO_ESCOLA_INFANTIL_TIPO_B_CONVENCIONAL_PAC", 73);
define("OBRA_TIPO_ESCOLA_INFANTIL_TIPO_B_CONVENCIONAL_PAR", 74);
define("OBRA_TIPO_ESCOLA_INFANTIL_TIPO_C_CONVENCIONAL_PAC", 75);
define("OBRA_TIPO_ESCOLA_INFANTIL_TIPO_C_CONVENCIONAL_PAR", 76);
// define("OBRA_TIPO_MI_TIPO_B_PROJETO_PROPRIO_PAC", 77);
// define("OBRA_TIPO_MI_TIPO_B_PROJETO_PROPRIO_PAR", 78);
// define("OBRA_TIPO_MI_TIPO_C_PROJETO_PROPRIO_PAC", 79);
// define("OBRA_TIPO_MI_TIPO_B_PROJETO_PROPRIO_PAR", 80);

# Workflow tipo documento
/*
  define("WF_FLUXO_PRO_INFANCIA", 	24);
  define("WF_TIPO_EM_CADASTRAMENTO", 	190);
  define("WF_TIPO_EM_ANALISE_FNDE", 	191);
  define("WF_TIPO_EM_CORRECAO", 		192);
 */

#FLUXO DOS PROGRAMAS EJA/EJA PRONATEC
define("WF_FLUXO_EJA_PRONATEC", 162);
define("WF_FLUXO_EJA_FINANCIA", 84);
define("WF_FLUXO_PRO_INFANCIA", 37);
define("WF_FLUXO_PRONATEC", 47);
define("WF_FLUXO_PROGRAMAS_FORMACAO", 41);
define("WF_FLUXO_OBRAS_PAR", 45);
define("WF_FLUXO_PRO_TRANSPORTE", 59);
define("WF_FLUXO_PRO_AGUA_ESCOLA", 77);

# PROINFANCIA
define("WF_TIPO_EM_CADASTRAMENTO", 193);
define("WF_TIPO_EM_ANALISE_FNDE", 194);
define("WF_TIPO_EM_CORRECAO", 195);
define("WF_TIPO_EM_REFORMULACAO", 360);
define("WF_TIPO_EM_REFORMULACAO_OBRAS_MI", 683);
define("WF_TIPO_ANALISE_DE_REFORMULACAO_OBRAS_MI", 754);
define("WF_TIPO_EM_REFORMULACAO_MI_PARA_CONVENCIONAL", 1486);
define("WF_TIPO_EM_DILIGENCIA_REFORMULACAO", 1657);
define("WF_TIPO_EM_DILIGENCIA_REFORMULACAO_MI_PARA_CONVENCIONAL", 1548);
define("WF_TIPO_EM_DILIGENCIA_SOLICITACAO_REFORMULACAO_MI_PARA_CONVENCIONAL", 1578);
define("WF_TIPO_EM_ANALISE_REFORMULACAO_MI_PARA_CONVENCIONAL", 1487);
define("WF_TIPO_EM_ANALISE_REFORMULACAO_MI_PARA_CONVENCIONAL_RETORNO_DILIGENCIA", 1564);
define("WF_TIPO_EM_VALIDACAO_DEFERIMENTO_REFORMULACAO_MI_PARA_CONVENCIONAL", 1553);
define("WF_TIPO_EM_VALIDACAO_INDEFERIMENTO_REFORMULACAO_MI_PARA_CONVENCIONAL", 1552);
define("WF_TIPO_EM_AGUARDANDO_VALIDACAO_REFORMULACAO_MI_PARA_CONVENCIONAL", 1561);
define("WF_TIPO_EM_ANALISE_SOLICITACAO_REFORMULACAO_MI_PARA_CONVENCIONAL_RETORNO_DILIGENCIA", 1579);
define("WF_TIPO_EM_VALIDACAO_GESTOR_MI_PARA_CONVENCIONAL", 1550);
define("WF_TIPO_EM_ANALISE_REFORMULACAO", 365);
define("WF_TIPO_EM_VALIDACAO_INDEFERIMENTO_REFORMULACAO", 366);
define("WF_TIPO_EM_VALIDACAO_DEFERIMENTO_REFORMULACAO", 367);

define("WF_AEDID_EM_REFORMULACAO_MI_CONV_PARA_ATUALIZACAO", 4974); /*RMC - Em Reformulação MI para Convencional*/
define("WF_AEDID_OBRA_APROVADA_PARA_ATUALIZACAO", 4982); /*Obra aprovada*/
define("WF_AEDID_ANALISE_REFORMULACAO_MI_CONV_PARA_ATUALIZACAO", 4975); /*RMC - Em Análise da Reformulação MI para Convencional*/
define("WF_AEDID_DILIGENCIA_REFORMULACAO_MI_CONV_PARA_ATUALIZACAO", 4976); /*RMC - Em Diligência da Reformulação MI para Convencional */
define("WF_AEDID_ANALISE_RETORNO_MI_CONV_PARA_ATUALIZACAO", 4977); /*RMC - Em Análise da Reformulação MI para Convencional / Retorno de Diligência*/
define("WF_AEDID_DEFERIMENTO_REFORMU_MI_CONV_PARA_ATUALIZACAO", 4978); /*RMC - Validação de Deferimento de Reformulação MI para Convencional*/
define("WF_AEDID_VALIDA_GESTOR_REFORM_MI_CONV_PARA_ATUALIZACAO", 4979); /*RMC - Validação do Gestor da Reformulação MI para Convencional*/
define("WF_AEDID_INDEFERIMENTO_REFORM_MI_CONV_PARA_ATUALIZACAO", 4980); /*RMC - Validação de Indeferimento de Reformulação MI para Convencional*/

define("GRUPO_SITUACAO_RMC_OBRA_PAC", serialize(ARRAY(WF_TIPO_EM_REFORMULACAO_MI_PARA_CONVENCIONAL, WF_TIPO_EM_ANALISE_REFORMULACAO_MI_PARA_CONVENCIONAL, WF_TIPO_EM_VALIDACAO_GESTOR_MI_PARA_CONVENCIONAL,
														WF_TIPO_EM_VALIDACAO_INDEFERIMENTO_REFORMULACAO_MI_PARA_CONVENCIONAL, WF_TIPO_EM_VALIDACAO_DEFERIMENTO_REFORMULACAO_MI_PARA_CONVENCIONAL,
														WF_TIPO_EM_AGUARDANDO_VALIDACAO_REFORMULACAO_MI_PARA_CONVENCIONAL, WF_TIPO_EM_ANALISE_REFORMULACAO_MI_PARA_CONVENCIONAL_RETORNO_DILIGENCIA,
														WF_TIPO_EM_DILIGENCIA_SOLICITACAO_REFORMULACAO_MI_PARA_CONVENCIONAL, WF_TIPO_EM_ANALISE_SOLICITACAO_REFORMULACAO_MI_PARA_CONVENCIONAL_RETORNO_DILIGENCIA,
														WF_TIPO_EM_DILIGENCIA_REFORMULACAO_MI_PARA_CONVENCIONAL)));

# Programa Transporte Escolar Acessivel
define("WF_PRO_TRANSPORTE_EM_CADASTRAMENTO", 426);
define("WF_PRO_TRANSPORTE_EM_DILIGENCIA", 428);

# Programa Água na Escola
define("WF_TIPO_AGUANAESCOLA_EM_CADASTRAMENTO", 530);
define("WF_TIPO_VALIDACAO_DILIGENCIA", 210);
define("WF_TIPO_VALIDACAO_INDEFERIMENTO", 211);
define("WF_TIPO_VALIDACAO_DEFERIMENTO", 212);
define("WF_TIPO_OBRA_INDEFERIDA", 213);
define("WF_TIPO_OBRA_DEFERIDA", 214);
define("WF_TIPO_EM_ANALISE", 215);
define("WF_TIPO_EM_ANALISE_VALIDACAO", 217);
define("WF_TIPO_EM_ANALISE_DILIGENCIA", 218);

# escolheu nao
define("WF_AEDID_ANALISE_FNDE_ENVIAR_VALIDACAO_INDEFERIMENTO", 514);
# escolheu sim
define("WF_AEDID_ANALISE_FNDE_ENVIAR_PARA_ANALISE", 515);

define("WF_AEDID_OBRA_APROVADA_ENVIAR_PARA_AGUARDANDO_PRORROGACAO", 1774);
define("WF_AEDID_AGUARDANDO_PRORROGACAO_ENVIAR_PARA_OBRA_APROVADA", 1775);

#Restricoes
define("WF_AEDID_ANALISE_PROVIDENCIAS_ENVIAR_PARA_CONCLUIDO", 2783);


#RESCISAO_TERMO
define("ESDID_OBJ_PLANEJAMENTO_PROPONENTE", 689);
define("ESDID_OBJ_LICITACAO", 763);
define("ESDID_OBJ_CONTRATACAO", 764);
define("ESDID_OBJ_EXECUCAO", 690);

define("AEDID_OBJ_PLANEJAMENTO_CANCELADO", 1861);
define("AEDID_OBJ_LICITACAO_CANCELADO", 1862);
define("AEDID_OBJ_CONTRATACAO_CANCELADO", 1863);
define("AEDID_OBJ_EXECUCAO_CANCELADO", 1864);
define("AEDID_OBJ_EXECUCAO_INACABADA", 3009);
define("AEDID_OBJ_PARALISADA_INACABADA", 3008);
define("AEDID_OBJ_LICITACAO_INACABADA", 2554);
define("AEDID_OBJ_CONTRATACAO_INACABADA", 2555);
#fluxo REscisao
define("AEDID_REST_CADASTRAMENTO_CONCLUIDA", 4132);
define("AEDID_REST_DILIGENCIA_CONCLUIDA", 4133);
define("AEDID_REST_TRAT_PROVI_CONCLUIDA", 4134);
define("AEDID_REST_ANA_DILIG_CONCLUIDA", 2794);


# PRONATEC
define("WF_PRONATEC_EM_CADASTRAMENTO", 347);
define("WF_PRONATEC_EM_ANALISE_FNDE", 348);
define("WF_PRONATEC_EM_ANALISE", 357);
define("WF_PRONATEC_EM_DILIGENCIA", 349);
define("WF_PRONATEC_VALIDACAO_DILIGENCIA", 345);
define("WF_PRONATEC_VALIDACAO_INDEFERIMENTO", 346);
define("WF_PRONATEC_VALIDACAO_DEFERIMENTO", 350);
define("WF_PRONATEC_OBRA_INDEFERIDA", 353);
define("WF_PRONATEC_OBRA_DEFERIDA", 354);
define("WF_PRONATEC_EM_REVISAO_DE_ANALISE", 351);
define("WF_PRONATEC_EM_ANALISE_RETORNO_DA_DILIGENCIA", 352);
define("WF_PRONATEC_OBRA_CONDICIONADA", 355);
define("WF_PRONATEC_OBRA_INDEFERIDA_PRAZO", 356);
define("WF_PRONATEC_OBRA_APROVADA", 358);
define("WF_PRONATEC_OBRA_ARQUIVADA", 359);

# escolheu nao
define("WF_PRONATEC_AEDID_ANALISE_FNDE_ENVIAR_VALIDACAO_INDEFERIMENTO", 913);
# escolheu sim
define("WF_PRONATEC_AEDID_ANALISE_FNDE_ENVIAR_PARA_ANALISE", 912);

# Contantes para montar a tabela de execução do PAR
define('TIPO_PAR', 1);
define('TIPO_OBRAS_PAR', 2);
define('TIPO_OBRAS_PAC', 3);

# Constantes Obras2
define("TPDID_OBJETO", 105);
define("OBR_ESDID_AGUARDANDO_1_REPASSE", 762);
define("OBR_ESDID_AGUARDANDO_ADESAO_DO_MUNICIPIO", 884);
define("OBR_ESDID_EM_EXECUCAO", 690);
define("OBR_ESDID_PARALISADA", 691);
define("OBR_ESDID_CONCLUIDA", 693);
define("OBR_ESDID_EM_ELABORACAO_DE_PROJETOS", 689);
define("OBR_ESDID_EM_LICITACAO", 763);
define("OBR_ESDID_CONTRATO_CANCELADO", 766);
define("OBR_ESDID_CONVENIO_CANCELADO", 767);
define("OBR_ESDID_EM_REFORMULACAO", 768);
define("OBR_ESDID_OBRA_CANCELADA", 769);
define("OBR_ESDID_ETAPA_CONCLUIDA", 770);
define("OBR_ESDID_AGUARDANDO_REGISTRO_DE_PRECOS", 771);
define("OBR_ESDID_EM_PLANEJAMENTO_PELO_PROPONENTE", 689);

# OBRAS PAC
define("WF_TPDID_FLUXO_OBRA_PAC", 37);
define("WF_TIPO_OBRA_CONDICIONADA", 220);
define("WF_TIPO_OBRA_INDEFERIDA_PRAZO", 221);
define("WF_TIPO_OBRA_APROVADA", 228);
define("WF_TIPO_OBRA_CANCELADA", 368);
define("WF_TIPO_OBRA_ARQUIVADA", 229);
define("WF_TIPO_OBRA_AGUARDANDO_PRORROGACAO", 755);
define("WF_TIPO_OBRA_APROVACAO_CONDICIONAL", 889);
define("WF_TIPO_PROFUNC_CADASTRAMENTO", 289);
define("WF_TIPO_PROFUNC_PREANALISE", 294);
define("WF_TIPO_PROFUNC_ANALISE", 295);
define("WF_TIPO_PROFUNC_MATRICULA", 296);
define("WF_TIPO_PNAIC_CADASTRAMENTO", 483);
define("WF_TIPO_PNAIC_PREANALISE", 484);
define("WF_TIPO_PNAIC_ANALISE", 485);
define("WF_TIPO_PNAIC_MATRICULA", 489);
define("WF_TIPO_OBRA_PRORROGACAO_CANCELADA", 1435); //PRODUCAO - 1435

# OBRAS PAR
define("WF_PAR_EM_CADASTRAMENTO", 326);
define("WF_PAR_EM_ANALISE_FNDE", 327);
define("WF_PAR_EM_ANALISE", 336);
define("WF_PAR_EM_DILIGENCIA", 328);
define("WF_PAR_VALIDACAO_DILIGENCIA", 324);
define("WF_PAR_VALIDACAO_INDEFERIMENTO", 325);
define("WF_PAR_VALIDACAO_DEFERIMENTO", 329);
define("WF_PAR_OBRA_INDEFERIDA", 332);
define("WF_PAR_OBRA_DEFERIDA", 333);
define("WF_PAR_EM_REVISAO_DE_ANALISE", 330);
define("WF_PAR_EM_ANALISE_RETORNO_DA_DILIGENCIA", 331);
define("WF_PAR_OBRA_CONDICIONADA", 334);
define("WF_PAR_OBRA_INDEFERIDA_PRAZO", 335);
define("WF_PAR_OBRA_APROVADA", 337);
define("WF_PAR_OBRA_ARQUIVADA", 338);
define("WF_PAR_OBRA_VAL_INDEF_REFORMULACAO", 366);
define("WF_PAR_OBRA_EM_REFORMULACAO", 624);
define("WF_PAR_OBRA_APROVACAO_SOLICITACAO_REFORMULACAO_MI_PARA_CONVENCIONAL", 1561);
define("WF_PAR_OBRA_EM_REFORMULACAO_MI_CONVENCIONAL", 1488);
define("WF_PAR_OBRA_EM_ANALISE_REFORMULAÇÃO", 625);
define("WF_PAR_OBRA_EM_DILIGENCIA_REFORMULACAO", 1658);
define("WF_PAR_OBRA_EM_ANALISE_REFORMULACAO_MI_CONVENCIONAL", 1489);
define("WF_PAR_OBRA_EM_ANALISE_REFORMULACAO_MI_CONVENCIONAL_RETORNO_DILIGENCIA", 1568);
define("WF_PAR_OBRA_EM_VALIDACAO_INDEFERIMENTO_REFORMULACAO", 626);
define("WF_PAR_OBRA_EM_VALIDACAO_DEFERIMENTO_REFORMULACAO", 627);
define("WF_PAR_OBRA_CANCELADA", 628);
define("WF_AEDID_OBRA_PAR_APROVADO_ENVIAR_EM_REFORMULACAO", 1581);
define("WF_AEDID_OBRA_PAR_APROVADO_ENVIAR_EM_REFORMULACAO_MI", 1770);
define("WF_AEDID_OBRA_PAR_CANCELA_REFORMULACAO", 1583);
define("WF_PAR_OBRA_EM_CADASTRAMENTO_CONDICIONAL", 827);
define("WF_PAR_OBRA_EM_APROVACAO_CONDICIONAL", 825);
define("WF_PAR_OBRA_AGUARDANDO_PRORROGACAO", 1260);
define("WF_AEDID_PAR_AGUARDANDO_PRORROGACAO_ENVIAR_PARA_OBRA_APROVADA", 2902);
define("WF_AEDID_PAR_AGUARDANDO_PRORROGACAO_ENVIAR_PARA_OBRA_RECUSADA", 3055);
define("WF_PAR_PRORROGACAO_CANCELADA", 1436); //PRODUCAO - 1436
define("WF_TIPO_EM_REFORMULACAO_MI_PARA_CONVENCIONAL_PAR", 1488);
define("WF_TIPO_EM_DILIGENCIA_REFORMULACAO_MI_PARA_CONVENCIONAL_PAR", 1549);
define("WF_TIPO_EM_ANALISE_REFORMULACAO_MI_PARA_CONVENCIONAL_PAR", 1489);
define("WF_TIPO_EM_VALIDACAO_DEFERIMENTO_REFORMULACAO_MI_PARA_CONVENCIONAL_PAR", 1566);
define("WF_TIPO_EM_VALIDACAO_GESTOR_MI_PARA_CONVENCIONAL_PAR", 1551);

# Ações OBRAS PAR
define("OBRA_AEDID_ENVIAR_PARA_REFORMULACAO_MI", 1772);
define("OBRA_AEDID_RETORNAR_PARA_EM_REFORMULACAO_MI", 1950);

# Tipo de OBRAS PAR
define("OBRA_PROJETO_PROPRIO", 16);

# PNAIC
define("WF_TIPO_PNAIC_CADASTRAMENTO", 483);

# Pergunta indeferimento
define("QUEST_PAR_INDEFERIMENTO", 2700);

# escolheu nao
define("WF_PAR_AEDID_ANALISE_FNDE_ENVIAR_VALIDACAO_INDEFERIMENTO", 858);
# escolheu sim

define("WF_PAR_AEDID_ANALISE_FNDE_ENVIAR_PARA_ANALISE", 859);
define("WF_AEDID_ANALISE_ENVIAR_VALIDACAO_DILIGENCIA", 522);
define("WF_AEDID_ANALISE_ENVIAR_VALIDACAO_DEFERIMENTO", 523);
define("WF_AEDID_ANALISE_ENVIAR_VALIDACAO_INDEFERIMENTO", 524);

define("WF_AEDID_APROVADO_ENVIAR_EM_REFORMULACAO", 976);

# Sistemas relacionados
define("SIS_OBRAS", 23);

# Grupos
define("TIPOMUN_GRUPO1", 150);
define("TIPOMUN_GRUPO2", 151);
define("TIPOMUN_GRUPO3", 152);

# novos grupos
define("TIPOMUN_GRUPO1_2011", 163);
define("TIPOMUN_GRUPO2_2011", 164);
define("TIPOMUN_GRUPO3_2011", 165);
/*
  define("SIS_OBRAS", 15);
 */

#PROGRAMAS ACESSADOS PELO PAR - DISPONIVEIS PARA ADESAO.
define("PROGRAMA_PROFUNCIONARIO", 1);
define("PROGRAMA_ESCOLA_GESTORES", 2);
define("PROGRAMA_PROINFANTIL", 3);
define("PROGRAMA_PRADIME", 4);
# define("PROGRAMA_ONIBUS_ACESSIVEL", 5); #Programa 2012
define("PROGRAMA_ONIBUS_ACESSIVEL", 11); #Programa 2013
define("PROGRAMA_PROCONSELHO", 6);
define("PROGRAMA_ALFABETIZACAO_IDADE_CERTA", 8);
define("PROGRAMA_AGUANAESCOLA", 9);

#PROGRAMA DE ADESÃO - ID.
define("PROGRAMA_EJA", 19);
define("PROGRAMA_CONSELHO_ESCOLAR", 13);
define("PROGRAMA_CORREPULA", 12);
define("PROGRAMA_PSE", 14);
define("PROGRAMA_EMI", 16);
define("PROGRAMA_ALFABETIZACAO_ENSINO_MEDIO", 18);
define("PROGRAMA_ESCOLA_TERRA", 15);
define("PROGRAMA_ATLETA2014", 20);
define("PROGRAMA_EJA_PRONATEC", 22);
define("PROGRAMA_ESCOLANACOPA", 24);
define("PROGRAMA_INSTRUTOR_CONSELHO_ESCOLAR", 25);

#PROGRAMAS ACESSADOS PELO PAR - TABELA PROGRAMAS.
define("PROG_PAR_PROFUNCIONARIO", 60);
define("PROG_PAR_ESCOLA_GESTORES", 12);
define("PROG_PAR_PROINFANTIL", 121);
define("PROG_PAR_PRADIME", 9);
define("PROG_PAR_ONIBUS_ACESSIVEL", 153);
define("PROG_PAR_PROCONSELHO", 155);
define("PROG_PAR_ALFABETIZACAO_IDADE_CERTA", 157);
define("PROG_PAR_AGUANAESCOLA", 183);
define("PROG_PAR_EJA", 188);
define("PROG_PAR_CONSELHO_ESCOLAR", 4);
define("PROG_PAR_CORREPULA", 218);
define("PROG_PAR_PSE", 219);
define("PROG_PAR_EMI", 220);
define("PROG_PAR_ALFABETIZACAO_ENSINO_MEDIO", 221);
define("PROG_PAR_ESCOLA_TERRA", 224);
define("PROG_PAR_MAIS_MEDICOS", 228);
define("PROG_PAR_ATLETA2014", 218);
define("PROG_PAR_ESCOLANACOPA", 248);
define("PROG_PAR_INSTRUTOR_CONSELHO_ESCOLAR", 247);

# Pró Funcionario
if ($_SESSION['baselogin'] == 'simec_desenvolvimento') {
    define("QUESTIONARIOPROMUN", 101); # municipal
    define("QUESTIONARIOPROEST", 102); # estadual
    define("PERGUNTA_1", 1729);
    define("PERGUNTA_2", 1720);
    if ($_SESSION['par']['itrid'] == 1) {
        define("RESPOSTA1_BLOQUEIA_PROFUN", 3197);
    } else {
        define("RESPOSTA1_BLOQUEIA_PROFUN", 3162);
    }
    define("FUNID_PROFESSOR_TUTOR", 84);
    define("FUNID_COORDENADOR_PROFUN", 83);
} else {
    define("QUESTIONARIOPROMUN", 59); # municipal
    define("QUESTIONARIOPROEST", 60); # estadual
    define("PERGUNTA_1", 1567);
    define("PERGUNTA_2", 1558);
    if ($_SESSION['par']['itrid'] == 1) {
        define("RESPOSTA1_BLOQUEIA_PROFUN", 3026);
    } else {
        define("RESPOSTA1_BLOQUEIA_PROFUN", 3012);
    }
    define("FUNID_PROFESSOR_TUTOR", 88);
    define("FUNID_COORDENADOR_PROFUN", 87);
}

# Plano de Apoio
define("NENHUMA_MODALIDADE", 7);

# Datas das travas do Pró Infância
define("DATA_EXPIRA_PROINFANCIA", "20101030000000");
# define("DATA_EXPIRA_PROINFANCIA_PENDENCIAS", "20103012170000");
define("DATA_EXPIRA_PROINFANCIA_PENDENCIAS2", "20110131235959");
define("DATA_EXPIRA_PROINFANCIA_PENDENCIAS", "20110114235959");
define("DATA_EXPIRA_PROINFANCIA_PENDENCIAS_G_1_e_2", "20120211235959");
define("DATA_EXPIRA_PROINFANCIA_PENDENCIAS_G_3", "20120415235959");

# Questões Analise
define("QUESTAO_DOCUMENTO1", 1299);
define("QUESTAO_DOCUMENTO2", 1301);
define("QUESTAO_FOTOS", 1303);
define("QUESTAO_PLANILHA", 1305);
define("QUESTAO_CRONOGRAMA", 1307);
define("QUESTAO_ESTUDO_DEM", 1309);
define("QUESTAO_PLANILHA_LOCALIZACAO", 1311);
define("QUESTAO_PLANILHA_SIT", 1313);
define("QUESTAO_PLANILHA_LOCACAO", 1315);
define("QUESTAO_PLANIALTIMETRICO", 1317);
define("QUESTAO_DOMINIALLIDADE", 1319);
define("QUESTAO_FORNECIMENTO_INFRA", 1321);
define("QUESTAO_COMPATIBILIDADE_FUNDACAO", 1322);

# Função entidades
define("FUNID_PREFEITURA", 1);
define("FUNID_PREFEITO", 2);
define("FUNID_ESCOLA", 3);
define("FUNID_SECRETARIA_MUNICIPAL_EDUCACAO", 7);
define("FUNID_SECRETARIA_ESTADUAL_EDUCACAO", 6);
define("FUNID_DIRIGENTE_MUNICIPAL_EDUCACAO", 15);
define("FUNID_SECRETARIO_ESTADUAL_EDUCACAO", 25);

# Tipo de Dados da Unidade
define("DUTID_DIRIGENTE", 2);
define("DUTID_EQUIPE_LOCAL", 3);
define("DUTID_COMITE_INTEGRANTES", 4);
define("DUTID_COMITE_COORDENADOR", 5);
define("DUTID_PREFEITURA", 6);
define("DUTID_PREFEITO", 7);
define("DUTID_SECRETARIA_MUNICIPAL", 8);
define("DUTID_SECRETARIA_ESTADUAL", 9);
define("DUTID_SECRETARIO_ESTADUAL", 10);

if ($_SESSION['baselogin'] == 'simec_desenvolvimento') {
    define("FUNID_COORDENADOR_PRO_FUNCIONARIO", 83);
    define("FUNID_PROF_TUTOR_PRO_FUNCIONARIO", 84);
    define("FUNID_CURSISTA_PROGRAMA_FORMACAO", 85);
} else {
    define("FUNID_COORDENADOR_PRO_FUNCIONARIO", 87);
    define("FUNID_PROF_TUTOR_PRO_FUNCIONARIO", 88);
    define("FUNID_CURSISTA_PROGRAMA_FORMACAO", 89);
}

# Cursos pro infância
define("CURSO_FORMACAO_PEDAGOGICA", 5);

# Datas
define("DATA_DADOS_UNIDADE_ATUALIZA", '2011-02-15');

if ($_SESSION['baselogin'] == 'simec_desenvolvimento') {
    define("QUESTOES_PONTUAIS_QUEID", '41');
    define("QUESTOES_PONTUAIS_ESCOLAS", '935');
} else {
    define("QUESTOES_PONTUAIS_QUEID", '58');
    define("QUESTOES_PONTUAIS_ESCOLAS", '1528');
}
/*
if ($_SESSION['baselogin'] == 'simec_desenvolvimento' || $_SESSION['baselogin'] == 'simec_espelho_producao') {
    define("USUARIO_SIGARP", 'MECVICTOR');
    define("SENHA_SIGARP", '27672463');
} else {*/
    define("USUARIO_SIGARP", 'USAP_WS_SIGARP');
    define("SENHA_SIGARP", '62856723');
//}
define("WS_USUARIO_SIGEF", 'USAP_WS_SIGARP');
define("WS_SENHA_SIGEF", '62856723');

# ID da licitação para as Obras MI
define("LICITACAO_MI", 23640);

# Origem da Pré-Obra
define("ORIGEM_OBRA_PAC2", 1);
define("ORIGEM_OBRA_PAR", 2);
define("ORIGEM_OBRA_PRONATEC", 3);
define("ORIGEM_OBRA_EMENDAS", 4);

# Exceções par
define("EXCECAO", 43);

/* * ** WORKFLOW PAR 2010 *** */
define("WF_DIAGNOSTICO", 313);
define("WF_ELABORACAO", 314);
define("WF_ANALISE", 315);

/* * ** TPDID DAS SUBACOES DO PAR *** */
define("WF_TPDID_SUBACOES_PAR", 62);

/* * ** WORKFLOW DAS SUBACAOES DO PAR *** */
define("WF_SUBACAO_ELABORACAO", 451);
define("WF_SUBACAO_ANALISE", 452);
define("WF_SUBACAO_GERACAO_TERMO_COOP", 453);
define("WF_SUBACAO_DILIGENCIA", 454);
define("WF_SUBACAO_APROVACAO_CONDICIONAL", 828);
define("WF_SUBACAO_DILIGENCIA_CONDICIONAL", 826);
define("WF_SUBACAO_AGUARDANDO_ANALISE_GESTOR", 455);
define("WF_SUBACAO_EMPENHO", 456);
define("WF_SUBACAO_PAGAMENTO", 457);
define("WF_SUBACAO_INDEFERIDA", 458);
define("WF_SUBACAO_APROVADA", 0);
define("WF_SUBACAO_ARQUIVADA", 0);
define("WF_SUBACAO_ANALISE_COMISSAO", 462);
define("WF_SUBACAO_RETORNADO_DE_DILIGENCIA", 1232);
define("WF_SUBACAO_BTN_ENVIAR_PARA_ANALISE", 1227);
define("WF_SUBACAO_BTN_ENVIAR_PARA_DILIGENCIA", 1229);
define("WF_SUBACAO_BTN_ENVIAR_PARA_EMPENHO", 1233);
define("WF_SUBACAO_ATUALIZACAO", 651);
define("WF_SUBACAO_ATUALIZACAO_ENVIAR_PARA_ANALISE", 1633);
define("WF_PAR_AEDID_ELABORACAO_ENVIAR_ANALISE", 1139);
/* * ** FIM WORKFLOW PAR 2010 *** */

# Escola Ativa
define('WF_TPDID_ESCOLA_ATIVA', 77);
define('PAR_ESCOLAATIVA_DATA_LIMITE_ADESAO', '20141230');

# Esta constante é o id do menu "Acompanhamento" que só deve estar disponível na própria página de acompanhamento do documento.
define("PAR_ESCONDE_ABA_ACOMPANHAMENTO", 13845);
define("PAR_ESCONDE_ABA_PRESTACAO_CONTAS", 18685);
define("PAR_ESCONDE_ABA_ESCOLATEMPOINTEGRAL", 17330);

# Tipos de Obra
define("OBR_TPOID_MI_TIPO_B", 104);
define("OBR_TPOID_MI_TIPO_C", 105);
define("OBR_TPOID_REFORMA", 17);
define("OBR_TPOID_AMPLIACAO", 18);
define("OBR_TPOID_REFORMA_UAB", 29);
define("OBR_TPOID_AMPLIACAO_UAB", 30);
define("OBR_TPOID_TIPO_A_EMENDA", 48);
define("OBR_TPOID_AMPLIACAO_EMENDA", 64);
define("OBR_TPOID_REFORMA_EMENDA", 65);
define("OBR_TPOID_AMPLIACAO_UAB_EMENDA", 66);
define("OBR_TPOID_REFORMA_UAB_EMENDA", 67);
define("OBR_TPOID_ESCOLA_PROJETO_PROPRIO", 16);
define("OBR_TPOID_ESCOLA_PROJETO_PROPRIO_EMENDA", 56);
define("OBR_TPOID_COBERTURA_DE_QUADRA_ESCOLAR_PROJETO_PROPRIO_EMENDA", 57);
define("OBR_TPOID_QUADRA_ESCOLAR_COBERTA_PROJETO_PROPRIO_EMENDA", 63);

# Modelos de Documentos - par.modelosdocumentos
define("MDOID_TERMO_COMPROMISSO_MUNICIPIOS", 20);
define("MDOID_TERMO_RESCISAO", 87);
define("TPDCOD_TERMO_RESCISAO", 104);
define("TPDCOD_RESCISAO", 105);
define("PRESIDENTE_FNDE", 'Antonio Idilvan de Lima Alencar');

if ($_SESSION['baselogin'] == 'simec_desenvolvimento') {
    # WORKFLOW - TIPO DE DOCUMENTO - Programa Mais Médicos
    define("WF_TPDID_MAIS_MEDICOS", 126);
    # WORKFLOW - TIPO DE DOCUMENTO - Programa Mais Médicos Novo Edital 2015
    define("WF_TPDID_MAIS_MEDICOS_NOVO_2015", 223);
    # QUESTIONARIO - Programa Mais Médicos
    define("QUEST_MAIS_MEDICOS", 89);
} else {
    # WORKFLOW - TIPO DE DOCUMENTO - Programa Mais Médicos
    define("WF_TPDID_MAIS_MEDICOS", 141);
    # WORKFLOW - TIPO DE DOCUMENTO - Programa Mais Médicos Novo Edital 2015
    define("WF_TPDID_MAIS_MEDICOS_NOVO_2015", 223);
    # QUESTIONARIO - Programa Mais Médicos
    define("QUEST_MAIS_MEDICOS", 89);
}

#ID DO PROGRAMA - PROGRAMA FINANCIAMENTO EJA.
define("PROG_PAR_PROGRAMA_FINANCIAMENTO_EJA", 188);

#ID DO PROGRAMA - EJA PRONATEC.
define("PROG_PAR_EJA_PRONATEC", 246);
#ID DO PROGRAMA - MAIS MÉDICO - NOVO EDITAL 2015.
define("PROG_PAR_MAIS_MEDICO_NOVO_2015", 251);

define("PROG_PAR_ADESAO_CONSELHO_ESCOLAR", 247);

#WORKFLOW - ESTADO DOCUMENTO - PROGRAMA FINANCIAMENTO EJA.
define("WF_EJA_EM_PREENCHIMENTO_UNIDADE", 565);
define("WF_EJA_EM_ANALISE_MEC", 566);
define("WF_EJA_CANCELADO", 567);
define("WF_EJA_APROVADO", 568);
define("WF_EJA_EM_DILIGENCIA", 572);

#WORKFLOW - ESTADO DOCUMENTO - PROGRAMA EJA PRONATEC.
define("WF_EJA_PRONATEC_EM_PREENCHIMENTO_UNIDADE", 1020);
define("WF_EJA_PRONATEC_EM_ANALISE_MEC", 1023);
define("WF_EJA_PRONATEC_CANCELADO", 1021);
define("WF_EJA_APRONATEC_PROVADO", 1024);
define("WF_EJA_PRONATEC_EM_DILIGENCIA", 1022);

#WORKFLOW - TIPO DE DOCUMENTO - PROGRAMA MAIS MÉDICO MEC - RECURSO QUESTIONÁRIO AVALIAÇÃO
define("WF_TPDID_MAIS_MEDICOS_RECURSO_QUESTIONARIO_AVALIACAO", 192);

#DATA DE FECHAMENTO DO RECURSO DO MUNICÍPIO MAIS MÉDICO.
define('DATA_FECHAMENTO_RECURSO', '2013-12-10GMT17:59:59');

#DATA DE FECHAMENTO DO RECURSO DO MUNICÍPIO MAIS MÉDICO PROGRAMA 2015.
define('DATA_FECHAMENTO_RECURSO_MAIS_MEDICO_2015', '2015-12-31GMT17:59:59');

#DATA DE FECHAMENTO DO RECURSO QUESTIONÁRIO AVALIAÇÃO MAIS MÉDICO.
define('DATA_FECHAMENTO_RECURSO_QUEST_AVAL', '2014-12-30GMT17:59:59');

# TIPO DE DOCUMENTO
define('TIPO_DE_DOCUMENTO_TERMO_ADITIVO', 21);
define('TIPO_DE_DOCUMENTO_TERMO_DE_COMPROMISSO', 102);
define('TIPO_DE_DOCUMENTO_TERMO_REFORMULADO', 103);

#WORKFLOW RESTRICOES PAR
define('TPDID_RESTRICAO_PAR', 193);
define('ESDID_EM_CADASTRAMENTO', 1216);
define('ESDID_EM_DILIGENCIA', 1217);
define('ESDID_EM_ANALISE_PROVIDENCIA', 1218);
define('ESDID_CONCLUIDO', 1219);
define('ESDID_EM_TRATATIVA_PROVIDENCIA', 1222);
define('ESDID_EM_ANALISE_DILIGENCIA', 1223);
define('TPRID_RESCISAO_TERMO', 11);

#SASE
define('SASE_COM_LEI_SANCIONADA', 9);

#SCHEMAEDUCASENSO
define('SCHEMAEDUCACENSO', 'educacenso_2014');

#Fluxo de Solicitacao de Prorrogacao de Prazo - Termo
define('TPDID_SOLICITACAO_PRORROGACAO_OBRA_TERMO', 250);
define('ESDID_AGUARDANDO_PRORROGACAO_PRAZO', 1669);
define('ESDID_EM_DILICIGENCIA', 1670);
define('ESDID_EM_DILICIGENCIA_INTERPOSICAO', 1910);
define('ESDID_ANALISE_CGIMP', 1671);
define('ESDID_ANALISE_CGESP', 1672);
define('ESDID_PRORROGACAO_PRAZO_APROVADA', 1673);
define('ESDID_PRORROGACAO_PRAZO_REPROVADA', 1674);
define('SDID_PRORROGACAO_PRAZO_APROVADA_RESSALVA', 1675);
define('ESDID_AGUARDANDO_GERACAO_TERMO', 1676);
define('ESDID_PRORROGACAO_PRAZO_FINALIZADA', 1677);
define('ESDID_AGUARDANDO_ANALISE_RECURSO', 1906);
define('ESDID_ANALISE_RECURSO_CGIMP', 1909);
define('ESDID_ANALISE_RECURSO_DIGAP', 1908);

define('AEDID_ENVIAR_ANALISE_RECURSO', 4604);
define('AEDID_DEFERIDO_PELA_DIGAP', 4829);
define('AEDID_INDEFERIDO_PELA_DIGAP', 4831);

define('TPDID_ACOMPANHAMENTO_PROCESSO', 270);
define('ESDID_EM_CADASTRAMENTO', 1807);
define('ESDID_EM_ANALISE_CACS', 1808);
define('ESDID_CONFIRMA_CACS', 1809);

define('AEID_CONFIRMA_CACS', 4384);
define('AEID_NAO_CONFIRMA_CACS', 4385);
define('AEID_CONFIRMA_RESSALVAS_CACS', 4386);


//define('TPDID_VALIDACAO_CAE', 274);
//define('ESDID_AGUARDANDO_VALIDACAO_FNDE', 1825);
//define('ESDID_VALIDADO_FNDE', 1826);
//define('ESDID_EM_DILIGENCIA', 1827);
//define('ESDID_AGUARDANDO_VALIDACAO_SIMEC', 1828);
//define('ESDID_RETORNO_DILIGENCIA', 1829);

/**
* Regra de data fim de vigencia apartir de 4/12/2015
* https://www.fnde.gov.br/fndelegis/action/UrlPublicasAction.php?acao=abrirAtoPublico&sgl_tipo=RES&num_ato=00000011&seq_ato=000&vlr_ano=2015&sgl_orgao=CD/FNDE/MEC
*/
define('DATA_INICIO_RESOLUCAO', '2015-12-04');

define('AEID_CONFIRMA_CACS', 4384);
define('AEID_NAO_CONFIRMA_CACS', 4385);
define('AEID_CONFIRMA_RESSALVAS_CACS', 4386);
/*
 * Fases da Prestação de contas do PAR
 * */
define('TPDID_FLUXO_PRESTACAO_CONTA', 303 );
define('ESDID_AGUARDANDO_ENVIO_PROPONENTE', 2005 );
define('ESDID_REGISTRO_EXECUCAO', 2005 );
define('ESDID_OPC_CONCLUIDA', 2299 );
define('ESDID_OPC_RESCINDIDA', 2301 );
define('ESDID_OPC_CANCELADA', 2300 );
define('ESDID_SITU_PC_SEM_VALOR_A_COMPROVAR',2304); 

define('ESDID_AGUARDANDO_ANALISE_CONSELHO', 2006 );
define('ESDID_AGUARDANDO_ANALISE_TECNICA_FNDE', 2105 );
define('AEDID_ENVIAR_ANALISE_CONSELHO', 4939);
define('AEDID_ENVIAR_ANALISE_TECNICA_FNDE', 5290);
define('AEDID_SITU_PC_ENVIAR_CACS_PARA_ANALISE_FNDE', 5635);
define('AEDID_SITU_PC_CACS_NOTIF_PARA_ANALISE_FNDE', 5800);  
define('AEDID_RETORNAR_MONITORAMENTO_PRESTACAO', 5295);
define('AEDID_SPC_RETORNO_CACS_NAO_ENVIADA', 5568);
define('ESDID_PC_ANALISE_DE_RETORNO_PARA_MONITORAMENTO', 2151 );

/*  SITUAÇÃO da Prestação de Contas do PAR*/
define('TPDID_FLUXO_SITUACAO_PRESTACAO_CONTAS', 335 );
define('ESDID_SPC_NAO_ENVIADA', 2236 );
define('ESDID_SPC_ENVIADA_AO_CONTROLE_SOCIAL', 2238 );
define('ESDID_SPC_AGUARDANDO_ANALISE', 2311 );
define('ESDID_NOTIFICADA_POR_OMISSAO', 2245 );
define('AEDID_SPC_NOTIFICAR_POR_OMISSAO', 5516);
define('AEDID_SPC_CACS_DECURSO_PRAZO', 5767);
define('AEDID_SPC_NOTIFICAR_CACS_POR_OMISSAO', 5770); 
define('AEDID_SPC_DE_NAO_ENVIADA_PARA_CONTROLE_SOCIAL', 5521); 
define('AEDID_SPC_DE_NOTIFICADA_PARA_CONTROLE_SOCIAL', 5522);  
define('ESDID_SPC_APROVACAO_PARCIAL', 2302);  
define('ESDID_SPC_APROVACAO_PARCIAL_RESSALVA', 2303);
define('ESDID_SPC_APROVACAO', 2310);
define('ESDID_SPC_APROVACAO_RESSALVA', 2313);
define('ESDID_SPC_DECURSO_PRAZO', 2305);
define('ESDID_SPC_NAO_APROVADA', 2312);
define('ESDID_SPC_NAO_LIBERADA', 2307);
define('ESDID_SPC_NOTIF_OCORRENCIA', 2314);
define('ESDID_SPC_OMISSO', 2309);
define('ESDID_SPC_NOTIFICADO_OMISSAO_CACS', 2449); 
define('ESDID_SPC_REPROVADA', 2306);
  
/* Situação da Prestação de Contas OBRAS */
define('TPDID_FLUXO_SIT_PC_EXEC_FINAN_OBRAS', 344 );
define('ESDID_SPC_OBRAS_APROVACAO_PARCIAL', 2280);
define('ESDID_SITUACAO_PC_NAO_ENVIADA', 2273 );
define('ESDID_SIT_PC_OBRAS_EM_ANALISE', 2286 );
define('AEDID_SPC_NOTIFICA_CACS_OMISSAO_OBRAS', 5768);
define('ESDID_OBRAS_NOTIFICADA_POR_OMISSAO', 2275 );
define('ESDID_PC_ENVIADA_AO_CONTROLE_SOCIAL', 2274 );
define('AEDID_OBRAS_NAO_ENVIADA_ENVIAR_AO_CONTROLE_SOCIAL', 5524);
define('AEDID_OBRAS_NOTIFICADA_POR_OMISSAO_ENVIAR_AO_CONTROLE_SOCIAL', 5525);
define('AEDID_OBRAS_ENVIAR_PRESTACAO_CONTAS', 5416);
define('ESDID_SPC_OBRAS_APROVACAO_PARCIAL_RESSALVA', 2281);
define('ESDID_SPC_OBRAS_APROVACAO', 2288);
define('ESDID_OBRAS_SPC_NOTIFICADO_OMISSAO_CACS',  2450); 
define('ESDID_SPC_OBRAS_APROVACAO_RESSALVA', 2291);
define('ESDID_SPC_OBRAS_DECURSO_PRAZO', 2283);
define('ESDID_SPC_OBRAS_NAO_APROVADA', 2290);
define('ESDID_SPC_OBRAS_NAO_LIBERADA', 2285);
define('ESDID_SPC_OBRAS_NOTIF_OCORRENCIA', 2292);
define('ESDID_SPC_OBRAS_OMISSO', 2287);
define('ESDID_SPC_OBRAS_REPROVADA', 2284);


/*  SITUAÇÃO da Obrigatoriedade de Prestar Contas*/
define('TPDID_FLUXO_OBRIGATORIEDADE_DE_PRESTAR_CONTAS', 336 );
define('ESDID_OPC_ADIMPLENTE', 2237 ); 
define('ESDID_OPC_INADIMPLENTE', 2298 );
define('AEDID_OPC_DE_ADIMPLENTE_PARA_INADIMPLENTE', 5569 );
define('AEDID_OPC_DE_INADIMPLENTE_PARA_ADIMPLENTE', 5570 ); 

/* Fases da Prestação de contas do OBRAS */
define('TPDID_FLUXO_PC_EXECUCAO_FINANCEIRA_OBRAS', 328 );
define('ESDID_PC_OBRAS_EM_CADASTRAMENTO', 2174 );
define('ESDID_OPC_OBRAS_CONCLUIDA', 2315 );
define('ESDID_SPC_OBR_SEM_VLR_A_COMPROVAR',2282); 


define('DPCID_OMISSAO_CACS', 5 );



define('ESDID_PC_ANALISE', 2277 );
define('ESDID_PC_CONTROLE_SOCIAL', 2175 );
define('AEDID_PC_RETORNO_MONITORAMENTO_APROVADO', 5392);



/* Situração da Obrigatoriedade de Prestas Contas OBRAS */
define('TPDID_FLUXO_SIT_OBRIG_PC_EXEC_FINAN_OBRAS', 345 );
define('ESDID_SITUACAO_PC_ADIMPLENTE', 2276 ); /* OPC OBRAS */
define('ESDID_OBRAS_SITUACAO_OPC_INADIMPLENTE', 2278 ); /* OPC OBRAS */
define('ESDID_OBRAS_OPC_RESCINDIDA', 2317 );
define('ESDID_OBRAS_OPC_CANCELADA', 2316 );
define('AEDID_OBRAS_OPC_DE_ADIMPLENTE_PARA_INADIMPLENTE', 5571 );
define('AEDID_OBRAS_SPC_NOTIFICAR_POR_OMISSAO', 5523);

/* ----------------------BEGIN----------------------
 * ESTADOS DA ANALISE TECNICA DA PRESTAÇÃO DE CONTAS
 * */
define('TPDID_ANALISE_TECNICA_PC', 358);
define('ESDID_ANALISETEC_INICIADA', 2386);

/* ----------------------END----------------------
 * */


/* ----------------------BEGIN----------------------
 * ESTADOS DA DILIGÊNCIA DA PRESTAÇÃO DE CONTAS 
 * */
define('ESDID_AGUARDANDO_ATENDIMENTO_DILIGENCIA_PC', 2152);
define('ESDID_ANALISE_PRORROGACAO_PRAZO_DILIGENCIA_PC', 2153);
define('ESDID_PRAZO_EXPIRADO_DILIGENCIA_PC', 2154);
define('ESDID_ENVIADO_PELO_ENTE_DILIGENCIA_PC', 2155);
define('ESDID_APROVADA_DILIGENCIA_PC', 2156);
define('ESDID_NAO_APROVADA_DILIGENCIA_PC', 2157);
/*Ações para estado "Aguardando Atendimento"*/
define('AEDID_SOLICITAR_PRORROGACAO_PRAZO_DILIGENCIA_PC', 5394);
define('AEDID_ANALISE_PRAZO_EXPIROU_DILIGENCIA_PC', 5395);
define('AEDID_ENVIAR_ANALISE_DILIGENCIA_PC', 5399);
/*Ações para estado "Prorrogação de Prazo - Aguardando Análise"*/
define('AEDID_ANALISE_PRORROGACAO_PRAZO_EXPIRADO_DILIGENCIA_PC', 5396);
define('AEDID_APROVAR_PRORROGACAO_PRAZO_DILIGENCIA_PC', 5397);
define('AEDID_REPROVAR_PRORROGACAO_PRAZO_DILIGENCIA_PC', 5398);
/*Ações para estado "Aguardando Análise - Enviada pelo Ente"*/
define('AEDID_APROVAR_DILIGENCIA_PC', 5400);
define('AEDID_REPROVAR_DILIGENCIA_PC', 5401);
/* ----------------------END----------------------
 * ESTADOS DA DILIGÊNCIA DA PRESTAÇÃO DE CONTAS
 * */

/*
 * BEGIN;
 * Constantes referentes aos ids dos tipos de possíveis ressalva de Exame de Formalidade da PRESTAÇÃO DE CONTAS
 * 1 - 'Forma de Contratação' ,2-'Documentos de Licitação' ,3-'Contrato' ,4-'Monitoramento' , 5-'Detalhamento' , 6,'Nota Fiscal' , 7-'Pagamento' , 8-'Forma de Contratação - Item não Previsto' ,
   9-'Documentos de Licitação - Item não Previsto' , 10 -'Contrato - Item não Previsto' , 11 -'Monitoramento - Item não Previsto' , 12 -'Detalhamento - Item não Previsto' , 13 -'Nota Fiscal - Item não Previsto' ,
   14 - 'Pagamento - Item não Previsto' ;
 * */
define('TRFID_FORMA_DE_CONTRATACAO', 1 );
define('TRFID_DOCUMENTOS_DE_LICITACAO', 2 );
define('TRFID_CONTRATO', 3 );
define('TRFID_MONITORAMENTO', 4 );
define('TRFID_DETALHAMENTO', 5 );
define('TRFID_NOTA_FISCAL', 6 );
define('TRFID_PAGAMENTO', 7 );
define('TRFID_FORMA_DE_CONTRATACAO_IT_N_PREVISTO', 8 );
define('TRFID_DOC_LICITACAO_IT_N_PREVISTO', 9 );
define('TRFID_CONTRATO_IT_N_PREVISTO', 10 );
define('TRFID_MONITORAMENTO_IT_N_PREVISTO', 11);
define('TRFID_DETALHAMENTO_IT_N_PREVISTO', 12 );
define('TRFID_NOTA_FISCAL_IT_N_PREVISTO', 13 );
define('TRFID_PAGAMENTO_IT_N_PREVISTO', 14 );
/*
 * BEGIN;
 * 
 * */


/*Tramites da rotina para tramitar a PC dos que não receberam recursos*/
define('AEDID_CACS_REGISTRO_SEM_SALDO', 5656);
define('AEDID_ANALISE_P_REGISTRO_SEM_SALDO', 5670);
define('AEDID_N_ENVIADA_SEM_VALOR', 5657); 
define('AEDID_CACS_P_SEM_VALOR', 5660); 
define('AEDID_ADIMP_CONCLIDA_S_SALDO', 5661); 
define('AEDID_OBR_ANALISE_P_REGISTRO_SEM_SALDO', 5662); 
define('AEDID_OBR_CACS_P_REGISTRO_SEM_SALDO', 5666); 
define('AEDID_OB_SIT_NAO_ENVI_P_SEM_VALOR', 5663); 
define('AEDID_OB_SIT_ANALISE_FNDE_P_SEM_VALOR', 5664); 
define('AEDID_OBR_SIT_CACS_P_SEM_VALOR', 5667); 
define('AEDID_OB_SIT_NOTIFICADA_P_SEM_VALOR', 5668); 
define('AEDID_OBR_OPC_ADIMPLENTE_P_CONCLUIDA', 5665); 
define('AEDID_OBR_OPC_INAADIMPLENTE_P_CONCLUIDA', 5669);
define('AEDID_OPC_ADIMPLENTE_P_CONCLUIDA', 5661);
define('AEDID_CACS_OBR_P_ANALISE', 5675);   
define('AEDID_SITU_CACS_OBR_P_ANALISE', 5676);
define('AEDID_SITU_CACS_NOTIF_OBR_P_ANALISE',5801 );

define('AEDID_OBRAS_SPC_NOTIFICAR_CACS_POR_OMISSAO', 5771 );    
   


/* ----------------------BEGIN----------------------
 * NOTIFICAÇÃO EX-GESTORES PRESTAÇÃO DE CONTAS
 * */
define('SITUACAO_NOTIFICACAO_EXGESTORES_INICIADO', 1);
define('SITUACAO_NOTIFICACAO_EXGESTORES_EXECUTADO_PARCIALMENTE', 2);
define('SITUACAO_NOTIFICACAO_EXGESTORES_FINALIZADO', 3);

/* ----------------------END----------------------
 * NOTIFICAÇÃO EX-GESTORES PRESTAÇÃO DE CONTAS
 * */



/* ----------------------BEGIN----------------------
 * ESTADOS DA PRESTAÇÃO DE CONTAS DE EX-GESTORES
 * */
define('TPDID_FLUXO_PC_EX_GESTOR', 394);
/*Estados*/
define('ESDID_PC_NAO_ENVIADA', 2427);
/*Ações para estado "Analise"*/
define('AEDID_ENVIAR_PARA_ANALISE', 5738);

/* ----------------------END----------------------
 * ESTADOS DA PRESTAÇÃO DE CONTAS DE EX-GESTORES
 * */


?>