<!DOCTYPE html>
<html>

<head>
    <meta charset="iso-8859-1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>SIMEC - Sistema Integrado de Monitoramento Execução e Controle</title>

    <link href="<?php echo $this->baseUrl("public/temas/simec/fonts/awesome/font-awesome.css"); ?>" rel="stylesheet">
    <link href="<?php echo $this->baseUrl("public/temas/simec/fonts/glyphicons/glyphicons.css"); ?>" rel="stylesheet">

    <link href="<?php echo $this->baseUrl("public/temas/simec/css/bootstrap.min.css"); ?>" rel="stylesheet">
    <link href="<?php echo $this->baseUrl("public/temas/simec/css/plugins/iCheck/custom.css"); ?>" rel="stylesheet">
    <link href="<?php echo $this->baseUrl("public/temas/simec/css/plugins/chosen/chosen.css"); ?>" rel="stylesheet">
    <link href="<?php echo $this->baseUrl("public/temas/simec/css/plugins/colorpicker/bootstrap-colorpicker.min.css"); ?>" rel="stylesheet">
    <link href="<?php echo $this->baseUrl("public/temas/simec/css/plugins/gritter/jquery.gritter.css"); ?>" rel="stylesheet">
    <link href="<?php echo $this->baseUrl("public/temas/simec/css/plugins/nouslider/jquery.nouislider.css"); ?>" rel="stylesheet">
    <link href="<?php echo $this->baseUrl("public/temas/simec/css/plugins/datapicker/datepicker3.css"); ?>" rel="stylesheet">
    <link href="<?php echo $this->baseUrl("public/temas/simec/css/plugins/bootstrap-switch/bootstrap-switch.css"); ?>" rel="stylesheet">
    <link href="<?php echo $this->baseUrl("public/temas/simec/css/plugins/treegrid/jquery.treegrid.css"); ?>" rel="stylesheet">
    <link href="<?php echo $this->baseUrl("public/temas/simec/css/plugins/nanoscroll/nanoscroller.css"); ?>" rel="stylesheet">
          
    <link href="<?php echo $this->baseUrl("public/temas/simec/css/animate.css"); ?>" rel="stylesheet">
    <link href="<?php echo $this->baseUrl("public/temas/simec/css/style.min.css"); ?>" rel="stylesheet">
    <link href="<?php echo $this->baseUrl("public/temas/simec/css/simec.css"); ?>" rel="stylesheet">

    <!-- Mainly scripts -->
    <script src="<?php echo $this->baseUrl("public/temas/simec/js/jquery-2.1.1.js"); ?>"></script>
    <script src="<?php echo $this->baseUrl("public/temas/simec/js/bootstrap.min.js"); ?>"></script>

    <script>
        $baseUrl = "<?php echo $this->baseUrl(); ?>";
        $themeUrl = "<?php echo $this->baseUrl("public/temas/simec"); ?>";
    </script>
</head>

<body class="pace-done fixed-sidebar">
<div id="barra-identidade">
    <div id="barra-brasil"></div>
    <script async="" defer="" type="text/javascript" src="http://barra.brasil.gov.br/barra.js"></script>
</div>

<!-- Header -->
<header id="top" class="header" style="display: none">
    <div class="row">
        <div class="col-lg-6 col-xs-6 col-sm-6" style="margin-top: 5px;">

        </div>

        <div class="col-lg-6 col-xs-6 col-sm-6 pull-right" style="margin-top: 5px;">
            <a href="http://www.brasil.gov.br/" class="brasil pull-right">
                <img style="margin-right: 10px;" src="http://portal.mec.gov.br/templates/mec2014/images/brasil.png"
                     alt="Brasil - Governo Federal" class="img-responsive">
            </a>
        </div>
    </div>
</header>

<?php $navigation = $this->navigation(); ?>

<div id="wrapper">
    <nav class="navbar-default navbar-static-side nano" role="navigation">
        <div class="sidebar-collapse nano-content">
            <?php echo $navigation['menu']; ?>
        </div>
    </nav>

    <div id="page-wrapper" class="gray-bg dashbard-1">
        <div class="row border-bottom">
            <nav class="navbar navbar-static-top" role="navigation" style="margin-bottom: 0;background: #273A4A") no-repeat">
                <div class="navbar-header hidden-md hidden-lg">
                    <a class="navbar-minimalize minimalize-styl-2 btn btn-primary" href="#"><i class="fa fa-bars"></i>
                    </a>
                </div>
                <ul class="nav navbar-top-links navbar-right pull-right" style="padding-top: 10px">
                    <li class="dropdown">
                        <div class="btn-group">
                    		<?php if (is_array($navigation['sistemas'])): ?>
                    		<?php foreach ($navigation['sistemas'] as $key => $temp) : ?>
                    		<?php if ($_SESSION['sisid'] == $temp['sisid']) $index = $key; ?>
                    		<?php endforeach; ?>
                        	<div class="btn-group">
						 		<button class="btn btn-sm dropdown-toggle" data-toggle="dropdown">
									<?php echo $navigation['sistemas'][$index]['sisabrev'] ?>&nbsp;
									<span class="caret"></span>
								</button>
								<ul class="dropdown-menu">
   									<?php foreach ($navigation['sistemas'] as $sistema): ?>
									<li>
										<a href="#" onclick="javascript:changeSystem(<?php echo $sistema['sisid'] ?>)">
										<?php echo $sistema['sisabrev'] ?>
										</a>
									</li>
									<?php endforeach ?>
								</ul>
							</div>
							<?php endif ?>
							
							<?php if (isset($navigation['exercicio']) && is_array($navigation['exercicio'])): ?>
							<div class="btn-group">
								<button class="btn btn-sm  dropdown-toggle" data-toggle="dropdown">
									<?php echo $_SESSION['exercicio'] ?>
									&nbsp;
									<span class="caret"></span>
								</button>
								<ul class="dropdown-menu">
									<li role="presentation" class="dropdown-header" style="padding-top: 12px;"><i class="glyphicon glyphicon-calendar"></i> Exercício</li>
										<li role="presentation" class="divider"></li>
   										<?php foreach ($navigation['exercicio'] as $anoExercicio): ?>
									<li>
										<a href="#" onclick="javascript:alteraTema(<?php echo $anoExercicio['codigo'] ?>)">
										<?php echo $anoExercicio['descricao'] ?>
										</a>
									</li>
									<?php endforeach ?>
								</ul>
								<script>
									function alteraTema(id) {
										$('#exercicio').val(id);
										document.getElementById('setperfil').submit();
									}
								</script>
							</div>
							<?php endif ?>
							
							<?php //if ($_SESSION['superuser'] == 1 || $exibirGraficoWorflow == true): ?>
							<div class="btn-group" title="Painel do workflow">
								<button data-toggle="modal" class="btn btn-sm" id="btPainelWorkflow">
									<i class="glyphicon glyphicon-stats"></i>
								</button>
							</div>
							
							<!-- Workflow -->
							<?php //if ($_SESSION['superuser'] == 1 || $_SESSION['usucpf'] != $_SESSION['usucpforigem'] || $exibirSimular == true || $db->testa_uma() || $_SESSION['usuuma']): ?>
							<div class="btn-group" title="Simular usuário">
								<?php if ($_SESSION['usucpf'] == $_SESSION['usucpforigem']): ?>
									<button data-toggle="modal" class="btn btn-sm" id="btSimularUsuario">
										<i class="glyphicon glyphicon-eye-open"></i>
									</button>
								<?php else: ?>
									<button class="btn btn-sm" id="voltar_usuario_origem">
										<i  class="glyphicon glyphicon-eye-close"></i>
									</button>
								<?php endif; ?>
							</div>
							<div class="btn-group" title="Gerenciar seus dados">
								<button onclick="javascript:window.location.href = '/seguranca/seguranca.php?modulo=sistema/usuario/cadusuario&acao=A&usucpf=<?php echo $_SESSION['usucpf'] ?>'" class="btn btn-sm">
									<i class="glyphicon glyphicon-wrench"></i>
								</button>
							</div>
							
							<div class="btn-group" title="Sair">
								<button onclick="javascript:window.location.href = '<?php echo $this->baseUrl() . '/usuario/logout'; ?>'" class="btn btn-sm">
									<i class="fa fa-sign-out"></i> Sair
								</button>
							</div>
						</div>
                    </li>
                </ul>
            </nav>
        </div>
        <?php $this->layout()->setLayout('default'); ?>
        <?php echo $this->layout()->render(); ?>
    </div>
</div>
<!-- Custom and plugin javascript -->
<script src="<?php echo $this->baseUrl("public/temas/simec/js/plugins/pace/pace.min.js"); ?>"></script>
<script src="<?php echo $this->baseUrl("public/temas/simec/js/plugins/slimscroll/jquery.slimscroll.min.js"); ?>"></script>

<!-- Chosen -->
<script src="<?php echo $this->baseUrl("public/temas/simec/js/plugins/chosen/chosen.jquery.js"); ?>"></script>

<!-- JSKnob -->
<script src="<?php echo $this->baseUrl("public/temas/simec/js/plugins/jsKnob/jquery.knob.js"); ?>"></script>

<!-- Data picker -->
<script src="<?php echo $this->baseUrl("public/temas/simec/js/plugins/datapicker/bootstrap-datepicker.js"); ?>"></script>

<!-- Switcher -->
<script src="<?php echo $this->baseUrl("public/temas/simec/js/plugins/bootstrap-switch/bootstrap-switch.js"); ?>"></script>

<!-- NanoScroller -->
<script src="<?php echo $this->baseUrl("public/temas/simec/js/plugins/nanoscroll/jquery.nanoscroller.min.js"); ?>"></script>

<!-- Treegrid -->
<script src="<?php echo $this->baseUrl("public/temas/simec/js/plugins/treegrid/jquery.treegrid.min.js"); ?>"></script>
<script src="<?php echo $this->baseUrl("public/temas/simec/js/plugins/treegrid/jquery.treegrid.bootstrap.js"); ?>"></script>

<!-- iCheck -->
<script src="<?php echo $this->baseUrl("public/temas/simec/js/plugins/iCheck/icheck.min.js"); ?>"></script>

<!-- File Input -->
<script src="<?php echo $this->baseUrl("public/temas/simec/js/plugins/fileinput/fileinput.min.js"); ?>"></script>
<script src="<?php echo $this->baseUrl("public/temas/simec/js/plugins/fileinput/fileinput_locale_pt-BR.js"); ?>"></script>

<!-- Masked Input -->
<script src="<?php echo $this->baseUrl("public/temas/simec/js/plugins/maskedinput/jquery.maskedinput.min.js"); ?>"></script>

<!-- Menu -->
<script src="<?php echo $this->baseUrl("public/temas/simec/js/plugins/metisMenu/jquery.metisMenu.js"); ?>"></script>

<!-- Datatables -->
<script src="<?php echo $this->baseUrl("public/temas/simec/js/plugins/dataTables/jquery.dataTables.js"); ?>"></script>
<script src="<?php echo $this->baseUrl("public/temas/simec/js/plugins/dataTables/dataTables.bootstrap.js"); ?>"></script>

<!-- Gritter -->
<script src="<?php echo $this->baseUrl("public/temas/simec/js/plugins/gritter/jquery.gritter.min.js"); ?>"></script>

<!-- Bootbox -->
<script src="<?php echo $this->baseUrl("public/temas/simec/js/plugins/bootbox/bootbox.min.js"); ?>"></script>

<!-- Validate -->
<script src="<?php echo $this->baseUrl("public/temas/simec/js/plugins/validate/jquery.validate.min.js"); ?>"></script>
<script src="<?php echo $this->baseUrl("public/temas/simec/js/plugins/validate/jquery.validate.extend.js"); ?>"></script>

<!-- Simec -->
<script src="<?php echo $this->baseUrl("public/temas/simec/js/simec.js"); ?>"></script>
</body>
</html>
