<div class="jsTelaDePesquisa">
    <script type="text/javascript" src="../includes/funcoes.js"></script>
    <div class="templates" style="display: none">
        <label class="btn btn-primary btn-campo js-tpl-radio" >
            <input type="radio" data-generate-name data-val-valor ><span data-html-descricao ></span>
        </label> 
        <select>
            <option class="js-tpl-option" data-val-valor data-html-descricao ></option>
        </select>
    </div>
    <div class="ibox" style="width:100%;">
        <form method="POST" name="pesquisa" id="formulario" class="form form-horizontal notprint" action="?modulo=par3/controle/relatorio-escola&acao=A&requisicao=pesquisarDadosDaListagem">
            <input type="hidden" name="tipoSaida" value="json">
            <input type="hidden" name="requisicao" value="">
            <input type="hidden" name="muncod_hid" value="">
            <div class="ibox-title">
                <div class="row">
                    <div class="col-md-10" >
                        <h3 id="entidade">Relatório de Escolas</h3>
                    </div>
                </div>
            </div>
            <div class="ibox-content">
                <div class="row">
                    <div class="col-lg-6 text-left">
                        <div class="form-group">
                            <label class="col-md-3 control-label">Colunas Adicionais: </label>
                            <div class="col-md-8">
                                <select data-collection="_JS.colunaOpcoes" data-tpl-item=".templates .js-tpl-option" name="sfiltro[colunas][]" multiple="multiple" data-placeholder="Colunas Adicionais" class="form-control chosen-select js-seletor-colunas" ></select>
                            </div>
                        </div>
                        <div class="form-group ">
                            <label class="col-md-3 control-label">Esfera: </label>
                            <div class="col-md-9">
                                <div data-collection="_JS.esferaOpcoes" data-tpl-item=".templates .js-tpl-radio" data-options-name="sfiltro[itrid]" class="btn-group js-seletor-esfera" data-toggle="buttons" ></div>
                            </div>
                        </div>
                        <div class="form-group ">
                            <label class="col-md-3 control-label">Unidade Federativa: </label>
                            <div class="col-md-8">
                                <select data-collection="_JS.estadoOpcoes" data-tpl-item=".templates .js-tpl-option" name="sfiltro[estuf][]" multiple="multiple" data-placeholder="Unidade Federativa" class="form-control chosen-select js-uf" ></select>
                            </div>
                        </div>
                        <div class="js-linha-municipio">
                            <div class="form-group ">
                                <label class="col-md-3 control-label">Município: </label>
                                <div class="col-md-8">
                                    <select name="sfiltro[mundescricao][]" multiple="multiple" data-placeholder="Município" class="form-control chosen-select js-municipio" ></select>
                                </div>
                            </div>
                        </div>
                        <div class="form-group ">
                            <label class="col-md-3 control-label">Situação: </label>
                            <div class="col-md-8">
                                <select data-collection="_JS.situacaoOpcoes" data-tpl-item=".templates .js-tpl-option" name="sfiltro[esdid][]" multiple="multiple" data-placeholder="Situação" class="form-control chosen-select js-seletor-colunas" ></select>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-6 text-left">
                        <div class="form-group ">
                            <label class="col-md-3 control-label">INEP: </label>
                            <div class="col-md-8">
                                <input name="sfiltro[inep]" type="text" value="" class="form-control">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-md-3 control-label">Nome: </label>
                            <div class="col-md-8">
                                <input name="sfiltro[nome]" type="text" value="" class="form-control">
                            </div>
                        </div>
                        <!-- -->
                        <div class="form-group ">
                            <label class="col-md-3 control-label">Possui Planejamento: </label>
                            <div class="col-md-9">
                                <div data-collection="_JS.planejamentoOpcoes" data-tpl-item=".templates .js-tpl-radio" data-options-name="sfiltro[planejamento]" class="btn-group js-seletor-planejamento" data-toggle="buttons"></div>
                            </div>
                        </div>
                        <div class="form-group form-inpid" style="display: none;">
                            <label class="col-md-3 control-label">Planejamento: </label>
                            <div class="col-md-8">
                                <input name="sfiltro[inpid]" type="text" value="" class="form-control">
                            </div>
                        </div>
                        <div class="form-group form-pronumeroprocesso" >
                            <label class="col-md-3 control-label">Processo: </label>
                            <div class="col-md-8">
                                <input
                                    name="sfiltro[pronumeroprocesso]"
                                    type="text"
                                    value=""
                                    class="form-control"
                                    maxlength="255"
                                    onkeyup="this.value=mascaraglobal('#####.######/####-##',this.value)"
                                    onblur="MouseBlur(this);this.value=mascaraglobal('#####.######/####-##',this.value);"
                                    autofocus="autofocus"
                                >
                            </div>
                        </div>
                        <div class="form-group form-dotnumero" >
                            <label class="col-md-3 control-label">Termo: </label>
                            <div class="col-md-8">
                                <input
                                    name="sfiltro[dotnumero]"
                                    value=""
                                    class="form-control"
                                    type ="number"
                                >
                            </div>
                        </div>
                    </div>
                </div>
                <div class="ibox-footer">
                    <div class="row">
                        <div class="col-lg-5 col-lg-offset-5">
                            <button type="button" class="btn btn-success buscar" style="width:110px;">
                                <i class="fa fa-search"></i> Filtrar
                            </button>
                            <button type="button" class="btn btn-primary xls" style="width:110px;">
                                <i class="fa fa-file-excel-o"></i> XLS
                            </button>
                        </div>
                        <button type="button" class="btn btn-info pull-right" id="btn-sql" style="display: none;"><i class="fa fa-database"></i></button>
                    </div>
                    <div class="row" >
                        <pre style="display: none;" id="panel-sql"></pre>
                    </div>
                </div>
            </div>
        </form>
    </div>
    <div class="ibox" style="width:100%;">
        <div class="ibox-content js-resultado-pesquisa" style="display:none">
            <div class="row">
                <div class="navbar-form navbar-left" >
                    <span data-html-totalRegistros ></span> registros encontrados.
                </div>
                <div class="navbar-form navbar-pesquisa navbar-right">
                    <div class="input-group">
                        <div class="input-group-addon" data-toggle="popover" style="cursor:pointer" data-original-title="" title="">
                            <span class="glyphicon glyphicon-info-sign" style="color:#428bca" data-original-title="" title=""></span>
                        </div>
                        <input class="form-control js-busca-no-resultado" placeholder="Digite o texto para busca" type="text">
                    </div>
                </div>
                <div class="navbar-form navbar-right" style="text-align:right;font-weight:bold">
                    <span>Pesquisa<br>rápida:</span>
                </div>
            </div>
            <table class="table table-striped table-bordered table-hover table-condensed tabela-listagem table-responsive">
                <thead>
                    <tr class="js-colunas-listagem">
                        <th></th>
                        <th>INEP</th>
                        <th>Munícipio</th>
                        <th>UF</th>
                        <th>IBGE</th>
                        <th>Esfera</th>
                        <th>Nome</th>
                        <th>Situação</th>
                        <th>Localização</th>
                        <th>Salas utilizadas</th>
                        <th>Total Alunos</th>
                        <th class="js-col-extra js-col-1">Imóvel</th>
                        <th class="js-col-extra js-col-2">Endereço</th>
                        <th class="js-col-extra js-col-3">CEP</th>
                        <th class="js-col-extra js-col-4">Coordenadas</th>
                        <th class="js-col-extra js-col-5">Total de Salas</th>
                        <th class="js-col-extra js-col-6">Alunos Infantil</th>
                        <th class="js-col-extra js-col-7">Alunos Fundamental</th>
                        <th class="js-col-extra js-col-8">Alunos Médio</th>
                        <th class="js-col-extra js-col-9">Planejamento</th>
                    </tr>
                </thead>
                <tbody class="templates" style="display:none">
                    <tr class="item-listagem">
                        <td ><a class="btn btn-primary btn-sm glyphicon glyphicon-eye-open js-visualizar-registro" href="javascript:void(0);"></a></td>
                        <td data-html-inep data-attr-escid="data-escid" ></td>
                        <td data-html-municipio ></td>
                        <td data-html-uf ></td>
                        <td data-html-ibge ></td>
                        <td data-html-esfera ></td>
                        <td data-html-nome ></td>
                        <td data-html-situacao ></td>
                        <td data-html-localizacao ></td>
                        <td data-html-salasUtilizadas ></td>
                        <td data-html-totalAlunos ></td>
                        <td class="js-col-extra js-col-1" data-html-imovel ></td>
                        <td class="js-col-extra js-col-2" data-html-endereco ></td>
                        <td class="js-col-extra js-col-3" data-html-cep ></td>
                        <td class="js-col-extra js-col-4" data-html-coordenadas ></td>
                        <td class="js-col-extra js-col-5" data-html-totalDeSalas ></td>
                        <td class="js-col-extra js-col-6" data-html-alunosInfantil ></td>
                        <td class="js-col-extra js-col-7" data-html-alunosFundamental ></td>
                        <td class="js-col-extra js-col-8" data-html-alunosMedio ></td>
                        <td class="js-col-extra js-col-9" data-html-planejamento ></td>
                    </tr>
                </tbody>
                <tbody class="listagem">
                </tbody>
            </table>
            <div class="row">
                <div class="col-md-12 text-center">
                    <a href="javascript:void(0);" class="js-mais-registros btn btn-primary" style="display:none;margin-bottom: 30px;">Mais Registros</a>
                </div>
            </div>
        </div>
    </div>

    <!-- Modal -->
    <div class="modal fade js-modal-registro" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog modal-lg js-registro" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="btn btn-info pull-left" id="btn-detalhe-sql" style="display: none;"><i class="fa fa-database"></i></button>
                    <button type="button" class="close pull-right" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <div class="row" >
                        <h4 class="modal-title text-center" id="myModalLabel">Detalhes da escola:
                            (<span data-html-inep ></span>) -
                            <span data-html-nome ></span>
                        </h4>
                        <pre style="display: none;" id="panel-detalhe-sql"></pre>
                    </div>
                </div>
                <div class="modal-body">
                    <div class="col-md-4">
                        <div class="form-group">
                            <label>UF:</label>
                            <span data-html-uf ></span>
                        </div>
                        <div class="form-group">
                            <label>Município:</label>
                            <span data-html-municipio ></span>
                        </div>
                        <div class="form-group">
                            <label>IBGE:</label>
                            <span data-html-ibge ></span>
                        </div>
                        <div class="form-group">
                            <label>Esfera:</label>
                            <span data-html-esfera ></span>
                        </div>

                    </div>
                    <div class="col-md-4">
                        <div class="form-group">
                            <label>Localização:</label>
                            <span data-html-localizacao ></span>
                        </div>
                        <div class="form-group">
                            <label>Situação:</label>
                            <span data-html-situacao ></span>
                        </div>
                        <div class="form-group">
                            <label>Total de salas:</label>
                            <span data-html-totalDeSalas ></span>
                        </div>
                        <div class="form-group">
                            <label>Salas utilizadas:</label>
                            <span data-html-salasUtilizadas ></span>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="form-group">
                            <label>Total Alunos:</label>
                            <span data-html-totalAlunos ></span>
                        </div>
                        <div class="form-group">
                            <label>Alunos Infantil:</label>
                            <span data-html-alunosInfantil ></span>
                        </div>
                        <div class="form-group">
                            <label>Alunos Fundamental:</label>
                            <span data-html-alunosFundamental ></span>
                        </div>
                        <div class="form-group">
                            <label>Alunos Médio:</label>
                            <span data-html-alunosMedio ></span>
                        </div>
                    </div>
                    <button type="button" class="btn btn-primary js-visualizar-mapa" data-attr-coordenadas="data-coordenadas" ><i class="glyphicon glyphicon-globe"></i> Visualizar mapa</button>
                    <div class="js-mapa">
                        <div id="map_canvas"></div>
                    </div>
                    <div class="js-resultado-itens-destinados">
                        <div class="form" >
                            <div class="form-group col-sm-6">
                                <label>Item:</label>
                                <select multiple="multiple" data-placeholder="Item" class="form-control chosen-select js-escola-item" ></select>
                            </div>
                            <div class="form-group col-sm-6">
                                <label>Processo:</label>
                                <select multiple="multiple" data-placeholder="Processo" class="form-control chosen-select js-escola-processo" ></select>
                            </div>
                            <div class="form-group col-sm-6">
                                <label>Situação:</label>
                                <select multiple="multiple" data-placeholder="Situação" class="form-control chosen-select js-escola-situacaoPlanejamento" ></select>
                            </div>
                            <div class="form-group col-sm-6">
                                <label>Termo:</label>
                                <select multiple="multiple" data-placeholder="Termo" class="form-control chosen-select js-escola-termo" ></select>
                            </div>
                        </div>
                        <table class="table table-striped table-bordered table-hover table-condensed tabela-listagem table-responsive">
                            <caption class="titulo-itens-destinados">Itens destinados à escola</caption>
                            <thead>
                                <tr>
                                    <th>Planejamento</th>
                                    <th style="width: 10%">Iniciativa</th>
                                    <th>Ano</th>
                                    <th style="width: 20%">Item</th>
                                    <th>Qtd. Planejada</th>
                                    <th>Qtd. Aprovada</th>
                                    <th>Qtd. Indicada(Emenda)</th>
                                    <th>Qtd. Monitorada</th>
                                    <th>Valor Unitário</th>
                                    <th>Valor Total</th>
                                    <th>Processo</th>
                                    <th>Termo</th>
                                    <th>Situação Planejamento</th>
                                    <th>Assistência</th>
                                </tr>
                            </thead>
                            <tbody class="templates" style="display:none">
                                <tr class="item-listagem-destinados">
                                    <td data-html-planejamento ></td>
                                    <td data-html-iniciativa ></td>
                                    <td data-html-ano ></td>
                                    <td data-html-item class="js-texto-item"></td>
                                    <td data-html-qtdPlanejada class="text-right"></td>
                                    <td data-html-aicqtdaprovado class="text-right"></td>
                                    <td data-html-quantidade_emenda class="text-right"></td>
                                    <td data-html-qtdMonitorada class="text-right"></td>
                                    <td data-html-valor ></td>
                                    <td data-html-valorTotal ></td>
                                    <td data-html-processo class="js-texto-processo"></td>
                                    <td data-html-termo class="js-texto-termo"></td>
                                    <td data-html-situacaoPlanejamento class="js-texto-situacaoPlanejamento"></td>
                                    <td data-html-tipoAssistencia ></td>
                                </tr>
                            </tbody>
                            <tbody class="listagem-destinados">
                            </tbody>
                        </table>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-primary" data-dismiss="modal">Fechar</button>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="jsTelaDeCadastro">
</div>
<script>
    setTimeout(function () {$('.chosen-select').trigger('chosen:updated')},1000);
</script>

