<div class="tpl-modal-historico-workflow" style="display:none;">
    <div class="modal-header">
    	<button type="button" class="bootbox-close-button close" data-dismiss="modal" aria-hidden="true">×</button>
    	<h4 class="modal-title">Histórico de tramitações</h4>
    </div>
    <div class="modal-body"></div>
    <div class="modal-footer">
    	<button type="button" class="btn btn-danger" data-dismiss="modal">
    		<span class="glyphicon glyphicon-remove"></span> Fechar
    	</button>
    </div>
</div>
