<?php
$linkGlobal = $linkGlobalCluster = null;

include_once APPRAIZ."includes/classe_simec.inc";

include_once APPRAIZ."includes/classes_simec_banco.inc";

include_once APPRAIZ."includes/classes_simec_criptografia.inc";

include_once APPRAIZ."includes/classes_simec_testes.inc";

include_once APPRAIZ."includes/classes_simec_gerar_excel.inc";

include_once APPRAIZ."includes/classes_simec_gerar_xml.inc";